### ISSUE TITLE
progressbar duplicate issue

### ISSUE THREAD

**Issue by onurkun** [drawRect/Instagram_Stories#94] opened 2020-04-19 17:36 UTC
**Describe the bug**
When I quickly switch between stories, old stories continue in the progressbar

**Screenshots**
[https://imgur.com/qEG8jqw](https://imgur.com/qEG8jqw)
.

**Comment by boominadhaprakash** [comment] 2020-04-19 18:40
Hi @onurkun 

Thanks for raising this issue. Please try the updated source code, related to progressor bar issue from **Boomi/issue89** branch.

Let us know, if that source code fixed your issue or not.

**Comment by onurkun** [comment] 2020-04-19 20:13
Not fixed my issue.

As a result of the reviews; when the video is switched to another story without being fully loaded, the previous video doesn't stop loading and starts working when the previous video is loaded.

**Comment by boominadhaprakash** [comment] 2020-04-20 11:57
Hi @onurkun 

It will be helpful for us, If you record your issue as a video and share it with us. Please confirm that are you using latest source code from master branch?

**Comment by onurkun** [comment] 2020-04-20 12:40
Yes. I am using latest sources and I tried Boomi/issue89 branch, it didn't work.
[https://drive.google.com/file/d/145l4kAdsR_HHh7u1ikzvKZTOs0dxU8e8/view?usp=sharing](https://drive.google.com/file/d/145l4kAdsR_HHh7u1ikzvKZTOs0dxU8e8/view?usp=sharing)

**Comment by boominadhaprakash** [comment] 2020-04-20 12:46
Thank you. Will check and let you know @onurkun

**Comment by onurkun** [comment] 2020-04-20 13:55
Thanks good work, I am waiting for your information.

**Comment by boominadhaprakash** [comment] 2020-04-23 13:54
Hi @onurkun 

We are unable to reproduce this issue. :(

**Comment by ranmyfriend** [comment] 2020-09-16 10:57
Closing this issue. Because of the long period of not getting this issue from anyone.
If anyone facing this feels free to reopen 👍

**Closed as completed by ranmyfriend** 2020-09-16 10:57 UTC
